### PR TITLE
Update nft.py

### PR DESCRIPTION
**Pull request by akhater**
The append in line 203 sets it to 'none' so I believe that what we shld be comparing it with

that's why the code wasn't finding any duplicates

### CODE REVIEW

**Review by levintech — CHANGES_REQUESTED** [review]
I used this condition and works well.

```
if rarity_dict[CONFIG[idx]['name']][index] != None:
    diff_count += 1
 if trait is not None:
     if rarity_dict[CONFIG[idx]['name']][index] != trait[: -1 * len('.png')]:
        diff_count += 1
```

Please check on your side and show me what's wrong on your side

**Comment by levintech** [comment]
Thanks for you attention to my update script. 
I had already sent change request for your script and mentioned my opinion.
Just now, I will close the pull request. If you found new one, please send me pull request.
Thanks again.

**Comment by akhater** [comment]
Your call my friend, I'm just letting you know that the code, as it is now, is not detecting duplicates

**Comment by levintech** [comment]
Thanks for your reply.
Okay, would you send pull request with your updated script? Of course, I assume you had already tested your script on your side.
Please send me request.
Best

**Comment by akhater** [comment]
> Thanks for your reply. Okay, would you send pull request with your updated script? Of course, I assume you had already tested your script on your side. Please send me request. Best

i did test your script and my modification off course. 

the change is already included in this pull request https://github.com/thunderstroke325/generative-art-nft/pull/2/files#diff-1e26af61f1a3fb0e4d4c57138dd88cfd998b035d665c30c1844df99ed1d56f9e

it is just changing `if rarity_dict[CONFIG[idx]['name']][index] != None:` to `if rarity_dict[CONFIG[idx]['name']][index] != 'none':`

**Comment by levintech** [comment]
Good job. thanks for your kindly effort.

**Pull request merged**
